### ISSUE TITLE
USER STORY: User can vote on a poll

### ISSUE THREAD

**Issue by marinamarshall** [marinamarshall/agile-repo#3]
As a **website user**, I can **vote on the poll displayed** so that **I can give my feedback**

## Acceptance Criteria:
- Select an option on the poll
- Save answer

## Tasks
- [ ] Design poll user interface
- [ ] Create HTML for poll and drop-down options
- [ ] Create CSS for poll
- [ ] Create radio/check-box for user to select
- [ ] Create submit button for user to submit answer
